package com.tastesync.oauth.db.queries;

public interface OAuthQueries {
    public static String DEVICE_IDENTIFIER_VENDOR_OAUTH_TOKEN_DELETE_SQL = "" +
        "DELETE FROM USER_DEVICE_OAUTH " +
        "WHERE USER_DEVICE_OAUTH.VENDOR_IDENTIFIER = ?";
    public static String DEVICE_TOKEN_INSERT_SQL = "" +
        "INSERT INTO USER_DEVICE_OAUTH " +
        " (USER_DEVICE_OAUTH.VENDOR_IDENTIFIER, " +
        " USER_DEVICE_OAUTH.DEVICE_TOKEN_EXPIRATION_DATETIME, " +
        " USER_DEVICE_OAUTH.DEVICE_TOKEN_UPDATED_DATETIME, " +
        " USER_DEVICE_OAUTH.MD5_OAUTH_TOKEN, " +
        " USER_DEVICE_OAUTH.OAUTH_EXPIRATION_DATETIME, " +
        " USER_DEVICE_OAUTH.OAUTH_UPDATED_DATETIME, " +
        " USER_DEVICE_OAUTH.USER_ID, USER_DEVICE_OAUTH.DEVICE_TYPE ) " +
        "VALUES ( ?, " + " ?, " + " ?, " + " ?, " + " ?, " + " ?, " +
        " ?, " + " ? )";
    public static String USER_DEVICE_TOKEN_SELECT_SQL = "" +
        "SELECT USER_DEVICE_OAUTH.USER_ID, " +
        "USER_DEVICE_OAUTH.MD5_OAUTH_TOKEN, " +
        "USER_DEVICE_OAUTH.DEVICE_TOKEN_EXPIRATION_DATETIME, " +
        "USER_DEVICE_OAUTH.DEVICE_TOKEN_UPDATED_DATETIME, " +
        "USER_DEVICE_OAUTH.OAUTH_UPDATED_DATETIME, " +
        "USER_DEVICE_OAUTH.OAUTH_EXPIRATION_DATETIME, " +
        "USER_DEVICE_OAUTH.DEVICE_TYPE " + "FROM USER_DEVICE_OAUTH " +
        "WHERE USER_DEVICE_OAUTH.VENDOR_IDENTIFIER = ? " +
        "AND replace(USER_DEVICE_OAUTH.MD5_OAUTH_TOKEN,'\r\n','')= ? ";
    
}
